#!/usr/bin/env bash
# Install Untype as a wrapper .app under /Applications.
#
# The bundle is a thin shim: its launcher binary exec's the `untype ui`
# command resolved at install time. The bundle does NOT embed Electron or
# the JS payload — it depends on the `untype` CLI being present on PATH
# (typically the pnpm global link at ~/Library/pnpm/untype).
#
# Re-run safely: the script is idempotent.

set -euo pipefail

APP_NAME="Untype"
BUNDLE_ID="com.untype.app"
DEFAULT_APPS_DIR="/Applications"
APPS_DIR="${UNTYPE_APPS_DIR:-$DEFAULT_APPS_DIR}"
APP_PATH="$APPS_DIR/$APP_NAME.app"
VERSION="$(node -p "require('$(cd "$(dirname "$0")/.." && pwd)/package.json').version")"

log()  { printf '\033[1;34m[install-macos-app]\033[0m %s\n' "$*"; }
fail() { printf '\033[1;31m[install-macos-app]\033[0m %s\n' "$*" >&2; exit 1; }

# 1. Resolve absolute paths at install time so the bundle does not depend on
#    the GUI session's PATH (Finder launches apps with a minimal PATH that
#    typically excludes /opt/homebrew/bin and ~/Library/pnpm).
PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENTRY_JS="$PROJECT_ROOT/dist/index.js"
[ -f "$ENTRY_JS" ] || fail "Entry point $ENTRY_JS not found. Run 'pnpm build' first."

NODE_BIN="${UNTYPE_NODE:-$(command -v node || true)}"
[ -n "$NODE_BIN" ] || fail "'node' not found. Set UNTYPE_NODE=/abs/path/to/node and re-run."
[ -x "$NODE_BIN" ] || fail "Resolved node ($NODE_BIN) is not executable."
log "Resolved node       -> $NODE_BIN"
log "Resolved entry      -> $ENTRY_JS"

# Capture parent directories so the launcher can extend PATH with the same
# locations the install ran under (Homebrew, pnpm shims, asdf, etc).
NODE_BIN_DIR="$(dirname "$NODE_BIN")"
PNPM_BIN_DIR="$HOME/Library/pnpm"

# 2. Sanity-check writability of the target Applications folder.
if [ ! -w "$APPS_DIR" ]; then
  fail "Cannot write to $APPS_DIR. Re-run with sudo, or set UNTYPE_APPS_DIR=$HOME/Applications."
fi

# 3. Remove any previous install so we start clean.
if [ -e "$APP_PATH" ]; then
  log "Removing existing bundle at $APP_PATH"
  rm -rf "$APP_PATH"
fi

# 4. Create the bundle skeleton.
log "Creating bundle at $APP_PATH"
mkdir -p "$APP_PATH/Contents/MacOS"
mkdir -p "$APP_PATH/Contents/Resources"

# 5. Write Info.plist.
cat > "$APP_PATH/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key>             <string>$APP_NAME</string>
  <key>CFBundleDisplayName</key>      <string>$APP_NAME</string>
  <key>CFBundleIdentifier</key>       <string>$BUNDLE_ID</string>
  <key>CFBundleVersion</key>          <string>$VERSION</string>
  <key>CFBundleShortVersionString</key><string>$VERSION</string>
  <key>CFBundlePackageType</key>      <string>APPL</string>
  <key>CFBundleExecutable</key>       <string>$APP_NAME</string>
  <key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
  <key>LSMinimumSystemVersion</key>   <string>11.0</string>
  <key>NSHighResolutionCapable</key>  <true/>
  <key>NSMicrophoneUsageDescription</key>
  <string>Untype streams microphone audio to a speech-to-text service to produce live transcripts.</string>
  <key>NSAppleEventsUsageDescription</key>
  <string>Untype may send key events to type transcripts into the focused application.</string>
</dict>
</plist>
PLIST

# 6. Write the launcher binary (a shell script). Hard-code the resolved CLI
#    path so a Finder launch doesn't depend on the GUI session's PATH.
LAUNCHER="$APP_PATH/Contents/MacOS/$APP_NAME"
cat > "$LAUNCHER" <<LAUNCH
#!/usr/bin/env bash
# Untype .app launcher — runs the CLI 'ui' subcommand directly via node.
# Generated by scripts/install-macos-app.sh — do not edit by hand.
set -euo pipefail

LOG_DIR="\$HOME/Library/Logs"
LOG_FILE="\$LOG_DIR/Untype.log"
mkdir -p "\$LOG_DIR"

# Extend PATH with the locations resolved at install time so any child
# processes (electron helper, uiohook, etc.) can find node + tooling.
export PATH="$NODE_BIN_DIR:$PNPM_BIN_DIR:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:\${PATH:-}"

# Tag log lines so successive launches are distinguishable.
{
  printf '\\n===== Untype launch %s =====\\n' "\$(date '+%Y-%m-%d %H:%M:%S')"
  printf 'node:  %s\\n' "$NODE_BIN"
  printf 'entry: %s\\n' "$ENTRY_JS"
  printf 'PATH:  %s\\n' "\$PATH"
} >> "\$LOG_FILE" 2>&1

cd "\$HOME"
exec "$NODE_BIN" "$ENTRY_JS" ui "\$@" >> "\$LOG_FILE" 2>&1
LAUNCH
chmod +x "$LAUNCHER"

# 7. Touch the bundle so Launch Services notices the change, then refresh.
touch "$APP_PATH"
if command -v /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister >/dev/null 2>&1; then
  /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister \
    -f "$APP_PATH" >/dev/null 2>&1 || true
fi

log "Installed $APP_NAME $VERSION at $APP_PATH"
log "Launch with:  open -a $APP_NAME    (or double-click in Finder)"
